### ISSUE TITLE
[eduadmin-listview] - Wrong sort order when using an event list

### ISSUE THREAD

**Issue by MNKevin** [MultinetInteractive/EduAdmin-WordPress#173] opened 2018-06-13 06:53 UTC
There's currently an issue with the sort order in the event lists.
Currently events are grouped by their CourseTemplate and sorted within this group, while older versions (1.X) didn't group events by their CourseTemplate.

This occurs when your using the setting: _Show events instead of courses_ or the attribute: _mode="events"_.

**Comment by itssimple** [comment] 2018-06-15 06:40
I think the API is giving me the wrong sort order back then.
Because I sort the events by date. https://github.com/MultinetInteractive/EduAdmin-WordPress/blob/master/content/template/listTemplate/list-events.php#L29

And the general sort order is by sort index: https://github.com/MultinetInteractive/EduAdmin-WordPress/blob/master/content/template/listTemplate/list-events.php#L72

**Comment by mansfalk** [comment] 2018-06-15 11:51
I think that the problem is that the events will get sorted within their course, and not all the events together. I might have to do the custom sorting manually after the events have been merged to one array and manually sorted by date. 

And also, is it by design that the event list page gets the data twice? First in list-events.php and then in edu-ajax-functions.php?

**Comment by itssimple** [comment] 2018-06-15 12:12
Yes, it is by design, since very many use caching plugins in their WordPress installations, which makes pages more or less static, so it's fetching the data for the static page, and then the ajax-functions fetches the data again, and replaces the container with the (possibly cached) events.

So yeah, since the API doesn't handle sorting like the old one did, we either have to make that work, or write a manual sorting-function to handle it.

**Comment by itssimple** [comment] 2018-06-25 09:55
Should've been closed with https://github.com/MultinetInteractive/EduAdmin-WordPress/releases/tag/v2.0.7

**Closed by itssimple** 2018-06-25 09:55 UTC
